import { motion } from "framer-motion";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { 
  Globe, BarChart3, FileCheck, Users, Ticket, Settings, 
  Palette, Shield, Smartphone, ArrowRight, Check 
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Link } from "react-router-dom";

const features = [
  {
    icon: Globe,
    title: "Branded Subdomain",
    description: "Get yourcoaching.univ.live as your professional web address. Optional custom domain support available.",
  },
  {
    icon: Palette,
    title: "AI-Generated Website",
    description: "Beautiful, responsive website generated by AI based on your coaching details and preferences.",
  },
  {
    icon: BarChart3,
    title: "Analytics Dashboard",
    description: "Real-time insights on student performance, enrollments, revenue, and test analytics.",
  },
  {
    icon: FileCheck,
    title: "Test Import & Creation",
    description: "Import tests from Excel/PDF or create new ones. Support for MCQ, subjective, and mixed formats.",
  },
  {
    icon: Users,
    title: "Access Code System",
    description: "Generate unique access codes for students. Control enrollment and manage batch-wise access.",
  },
  {
    icon: Ticket,
    title: "Support Ticketing",
    description: "Built-in ticketing system for student queries. Track and resolve issues efficiently.",
  },
];

const benefits = [
  "No technical knowledge required",
  "Website ready in ~6 hours",
  "Mobile-optimized design",
  "SEO-friendly structure",
  "Secure student data",
  "24/7 platform support",
];

export default function ForCoaching() {
  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      
      <main className="pt-24 pb-20">
        {/* Hero */}
        <section className="container mx-auto px-4 lg:px-8 py-16">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <motion.div
              initial={{ opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
            >
              <span className="inline-block px-4 py-1.5 rounded-full bg-brand-start/10 text-sm font-medium text-brand-blue mb-4">
                For Coaching Institutes
              </span>
              <h1 className="text-4xl sm:text-5xl font-display font-bold mb-6">
                Your Complete{" "}
                <span className="gradient-text">Digital Coaching</span>{" "}
                Solution
              </h1>
              <p className="text-xl text-muted-foreground mb-8">
                From professional website to student management — everything you need to run a modern coaching institute.
              </p>
              
              <div className="grid grid-cols-2 gap-3 mb-8">
                {benefits.map((benefit) => (
                  <div key={benefit} className="flex items-center gap-2">
                    <Check className="w-5 h-5 text-brand-blue shrink-0" />
                    <span className="text-sm">{benefit}</span>
                  </div>
                ))}
              </div>

              <div className="flex flex-wrap gap-4">
                <Button variant="hero" size="xl" asChild className="group">
                  <Link to="/signup?role=educator">
                    Start Free Trial
                    <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
                  </Link>
                </Button>
                <Button variant="outline" size="xl" asChild>
                  <Link to="/contact">Book Demo</Link>
                </Button>
              </div>
            </motion.div>

            {/* Dashboard Preview */}
            <motion.div
              initial={{ opacity: 0, x: 50 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.8, delay: 0.2 }}
              className="relative"
            >
              <div className="absolute inset-0 gradient-bg opacity-20 blur-3xl rounded-3xl" />
              <div className="relative bg-card rounded-2xl shadow-2xl border border-border/50 overflow-hidden">
                <div className="flex items-center gap-2 px-4 py-3 bg-secondary/50 border-b border-border">
                  <div className="flex gap-1.5">
                    <div className="w-3 h-3 rounded-full bg-destructive/60" />
                    <div className="w-3 h-3 rounded-full bg-yellow-500/60" />
                    <div className="w-3 h-3 rounded-full bg-green-500/60" />
                  </div>
                  <div className="flex-1 mx-4">
                    <div className="bg-background/60 rounded-lg px-4 py-1.5 text-xs text-muted-foreground text-center">
                      dashboard.univ.live
                    </div>
                  </div>
                </div>
                <div className="p-6 bg-gradient-to-br from-surface to-background">
                  <div className="grid grid-cols-2 gap-4 mb-4">
                    {[
                      { label: "Total Students", value: "1,247" },
                      { label: "Active Tests", value: "45" },
                      { label: "This Month", value: "₹2.8L" },
                      { label: "Avg Score", value: "72%" },
                    ].map((item) => (
                      <div key={item.label} className="bg-card rounded-xl p-4 border border-border/50">
                        <p className="text-xs text-muted-foreground">{item.label}</p>
                        <p className="text-xl font-bold gradient-text">{item.value}</p>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </motion.div>
          </div>
        </section>

        {/* Features */}
        <section className="container mx-auto px-4 lg:px-8 py-16">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <h2 className="text-3xl sm:text-4xl font-display font-bold mb-4">
              Everything Your Coaching Needs
            </h2>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              Comprehensive tools designed specifically for educational institutions.
            </p>
          </motion.div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map((feature, index) => (
              <motion.div
                key={feature.title}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.1 }}
                className="bg-card rounded-2xl p-6 border border-border/50 shadow-card hover:shadow-card-hover transition-all hover:-translate-y-1"
              >
                <div className="w-12 h-12 rounded-xl gradient-bg flex items-center justify-center mb-4">
                  <feature.icon className="w-6 h-6 text-white" />
                </div>
                <h3 className="text-lg font-semibold mb-2">{feature.title}</h3>
                <p className="text-sm text-muted-foreground">{feature.description}</p>
              </motion.div>
            ))}
          </div>
        </section>

        {/* CTA */}
        <section className="container mx-auto px-4 lg:px-8 py-16">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center bg-card rounded-3xl p-12 border border-border/50"
          >
            <h2 className="text-3xl font-display font-bold mb-4">
              Ready to Transform Your Coaching?
            </h2>
            <p className="text-lg text-muted-foreground mb-8 max-w-xl mx-auto">
              Join 500+ coaching institutes already using UNIV.LIVE
            </p>
            <Button variant="hero" size="xl" asChild className="group">
              <Link to="/signup?role=educator">
                Get Started Free
                <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
              </Link>
            </Button>
          </motion.div>
        </section>
      </main>

      <Footer />
    </div>
  );
}
